ci: # NOTE: uses https://pre-commit.ci
  autofix_prs: true
  autoupdate_schedule: weekly
  # skip: []

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [--fix, --select, I]
        types: [python]
      # Run the formatter.
      - id: ruff-format
        types: [python]
